/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerPath { 'name' : string, 'description' : string }
export interface CodeSubmission {
  'problemTitle' : string,
  'optimizationSuggestions' : Array<Optimization>,
  'language' : Language,
  'codeText' : string,
  'edgeCases' : Array<EdgeCase>,
  'tleRiskLevel' : TleRiskLevel,
  'timeComplexity' : Complexity,
  'submissionTime' : Time,
  'submissionId' : SubmissionId,
  'spaceComplexity' : Complexity,
}
export interface CodingStats {
  'totalEasyProblemsSolved' : bigint,
  'totalHardProblemsSolved' : bigint,
  'totalMediumProblemsSolved' : bigint,
  'totalProblemsSolved' : bigint,
  'optimizationImprovementPercent' : bigint,
  'completedProjects' : Array<Project>,
  'longestStreakDays' : bigint,
  'consistencyScore' : bigint,
  'currentDayStreak' : bigint,
}
export type Complexity = string;
export interface ComprehensiveUserRecordView {
  'roadmap' : Array<RoadmapEntry>,
  'codingStats' : CodingStats,
  'skillGaps' : Array<string>,
  'submissions' : Array<CodeSubmission>,
  'recommendedJobRoles' : Array<JobRole>,
  'resumeData' : ResumeData,
  'careerPathSuggestions' : Array<CareerPath>,
  'skillLevel' : SkillLevel,
  'profile' : StudentProfile,
}
export type EdgeCase = string;
export type InterviewFocus = string;
export type JobRole = string;
export type Language = string;
export type Optimization = string;
export type OptimizationTarget = number;
export interface Project {
  'name' : ProjectName,
  'description' : string,
  'techStack' : Array<TechStack>,
}
export type ProjectName = string;
export type ProjectSuggestion = string;
export interface ResumeData {
  'keyStrengths' : Array<string>,
  'strengthBreakdown' : ResumeStrengthBreakdown,
  'technicalSkills' : Array<string>,
  'projects' : Array<Project>,
  'strengthScore' : number,
  'codingAchievements' : string,
  'header' : ResumeHeader,
}
export interface ResumeHeader {
  'name' : string,
  'graduationYear' : bigint,
  'email' : string,
  'university' : string,
}
export interface ResumeStrengthBreakdown {
  'problemSolving' : number,
  'projectStrength' : number,
  'consistency' : number,
  'languageDepth' : number,
  'advancedProblemRatio' : number,
  'optimization' : number,
}
export interface RoadmapEntry {
  'problemsTargetCount' : bigint,
  'optimizationTargetPercent' : OptimizationTarget,
  'interviewFocus' : InterviewFocus,
  'weekNumber' : WeekNumber,
  'topics' : Array<Topic>,
  'projectSuggestion' : ProjectSuggestion,
}
export type SkillLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null } |
  { 'competitive' : null };
export interface StudentProfile {
  'primaryLanguages' : Array<Language>,
  'name' : string,
  'graduationYear' : bigint,
  'email' : string,
  'university' : string,
  'focusTopics' : Array<Topic>,
}
export type SubmissionId = bigint;
export type TechStack = string;
export type Time = bigint;
export type TleRiskLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Topic = string;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WeekNumber = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptCycles' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUserRecords' : ActorMethod<[], Array<ComprehensiveUserRecordView>>,
  'getAllUserRecordsByEmail' : ActorMethod<
    [],
    Array<ComprehensiveUserRecordView>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCareerPathSuggestions' : ActorMethod<[], Array<CareerPath>>,
  'getCodingStats' : ActorMethod<[], CodingStats>,
  'getProfile' : ActorMethod<[], StudentProfile>,
  'getRecommendedJobRoles' : ActorMethod<[], Array<string>>,
  'getResumeData' : ActorMethod<[], ResumeData>,
  'getResumeStrengthBreakdown' : ActorMethod<[], ResumeStrengthBreakdown>,
  'getResumeStrengthScore' : ActorMethod<[], number>,
  'getRoadmap' : ActorMethod<[], Array<RoadmapEntry>>,
  'getSkillGaps' : ActorMethod<[], Array<string>>,
  'getSkillLevel' : ActorMethod<[], SkillLevel>,
  'getSubmissionById' : ActorMethod<[SubmissionId], CodeSubmission>,
  'getUserProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'getUserRecordById' : ActorMethod<[UserId], ComprehensiveUserRecordView>,
  'getVersion' : ActorMethod<[], string>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listSubmissionsPaginated' : ActorMethod<
    [bigint, bigint],
    Array<CodeSubmission>
  >,
  'saveCallerUserProfile' : ActorMethod<[StudentProfile], undefined>,
  'submitCode' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      TleRiskLevel,
      Array<string>,
      Array<string>,
    ],
    CodeSubmission
  >,
  'updateCodingStats' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      Array<Project>,
    ],
    CodingStats
  >,
  'updateProfile' : ActorMethod<
    [string, string, string, bigint, Array<string>, Array<string>],
    StudentProfile
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];