/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OptimizationTarget = IDL.Nat8;
export const InterviewFocus = IDL.Text;
export const WeekNumber = IDL.Nat;
export const Topic = IDL.Text;
export const ProjectSuggestion = IDL.Text;
export const RoadmapEntry = IDL.Record({
  'problemsTargetCount' : IDL.Nat,
  'optimizationTargetPercent' : OptimizationTarget,
  'interviewFocus' : InterviewFocus,
  'weekNumber' : WeekNumber,
  'topics' : IDL.Vec(Topic),
  'projectSuggestion' : ProjectSuggestion,
});
export const ProjectName = IDL.Text;
export const TechStack = IDL.Text;
export const Project = IDL.Record({
  'name' : ProjectName,
  'description' : IDL.Text,
  'techStack' : IDL.Vec(TechStack),
});
export const CodingStats = IDL.Record({
  'totalEasyProblemsSolved' : IDL.Nat,
  'totalHardProblemsSolved' : IDL.Nat,
  'totalMediumProblemsSolved' : IDL.Nat,
  'totalProblemsSolved' : IDL.Nat,
  'optimizationImprovementPercent' : IDL.Nat,
  'completedProjects' : IDL.Vec(Project),
  'longestStreakDays' : IDL.Nat,
  'consistencyScore' : IDL.Nat,
  'currentDayStreak' : IDL.Nat,
});
export const Optimization = IDL.Text;
export const Language = IDL.Text;
export const EdgeCase = IDL.Text;
export const TleRiskLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Complexity = IDL.Text;
export const Time = IDL.Int;
export const SubmissionId = IDL.Nat64;
export const CodeSubmission = IDL.Record({
  'problemTitle' : IDL.Text,
  'optimizationSuggestions' : IDL.Vec(Optimization),
  'language' : Language,
  'codeText' : IDL.Text,
  'edgeCases' : IDL.Vec(EdgeCase),
  'tleRiskLevel' : TleRiskLevel,
  'timeComplexity' : Complexity,
  'submissionTime' : Time,
  'submissionId' : SubmissionId,
  'spaceComplexity' : Complexity,
});
export const JobRole = IDL.Text;
export const ResumeStrengthBreakdown = IDL.Record({
  'problemSolving' : IDL.Nat8,
  'projectStrength' : IDL.Nat8,
  'consistency' : IDL.Nat8,
  'languageDepth' : IDL.Nat8,
  'advancedProblemRatio' : IDL.Nat8,
  'optimization' : IDL.Nat8,
});
export const ResumeHeader = IDL.Record({
  'name' : IDL.Text,
  'graduationYear' : IDL.Nat,
  'email' : IDL.Text,
  'university' : IDL.Text,
});
export const ResumeData = IDL.Record({
  'keyStrengths' : IDL.Vec(IDL.Text),
  'strengthBreakdown' : ResumeStrengthBreakdown,
  'technicalSkills' : IDL.Vec(IDL.Text),
  'projects' : IDL.Vec(Project),
  'strengthScore' : IDL.Nat8,
  'codingAchievements' : IDL.Text,
  'header' : ResumeHeader,
});
export const CareerPath = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const SkillLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
  'competitive' : IDL.Null,
});
export const StudentProfile = IDL.Record({
  'primaryLanguages' : IDL.Vec(Language),
  'name' : IDL.Text,
  'graduationYear' : IDL.Nat,
  'email' : IDL.Text,
  'university' : IDL.Text,
  'focusTopics' : IDL.Vec(Topic),
});
export const ComprehensiveUserRecordView = IDL.Record({
  'roadmap' : IDL.Vec(RoadmapEntry),
  'codingStats' : CodingStats,
  'skillGaps' : IDL.Vec(IDL.Text),
  'submissions' : IDL.Vec(CodeSubmission),
  'recommendedJobRoles' : IDL.Vec(JobRole),
  'resumeData' : ResumeData,
  'careerPathSuggestions' : IDL.Vec(CareerPath),
  'skillLevel' : SkillLevel,
  'profile' : StudentProfile,
});
export const UserId = IDL.Principal;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptCycles' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUserRecords' : IDL.Func(
      [],
      [IDL.Vec(ComprehensiveUserRecordView)],
      ['query'],
    ),
  'getAllUserRecordsByEmail' : IDL.Func(
      [],
      [IDL.Vec(ComprehensiveUserRecordView)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCareerPathSuggestions' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
  'getCodingStats' : IDL.Func([], [CodingStats], ['query']),
  'getProfile' : IDL.Func([], [StudentProfile], ['query']),
  'getRecommendedJobRoles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getResumeData' : IDL.Func([], [ResumeData], ['query']),
  'getResumeStrengthBreakdown' : IDL.Func(
      [],
      [ResumeStrengthBreakdown],
      ['query'],
    ),
  'getResumeStrengthScore' : IDL.Func([], [IDL.Nat8], ['query']),
  'getRoadmap' : IDL.Func([], [IDL.Vec(RoadmapEntry)], ['query']),
  'getSkillGaps' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSkillLevel' : IDL.Func([], [SkillLevel], ['query']),
  'getSubmissionById' : IDL.Func([SubmissionId], [CodeSubmission], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getUserRecordById' : IDL.Func(
      [UserId],
      [ComprehensiveUserRecordView],
      ['query'],
    ),
  'getVersion' : IDL.Func([], [IDL.Text], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSubmissionsPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(CodeSubmission)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
  'submitCode' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        TleRiskLevel,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [CodeSubmission],
      [],
    ),
  'updateCodingStats' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(Project),
      ],
      [CodingStats],
      [],
    ),
  'updateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [StudentProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OptimizationTarget = IDL.Nat8;
  const InterviewFocus = IDL.Text;
  const WeekNumber = IDL.Nat;
  const Topic = IDL.Text;
  const ProjectSuggestion = IDL.Text;
  const RoadmapEntry = IDL.Record({
    'problemsTargetCount' : IDL.Nat,
    'optimizationTargetPercent' : OptimizationTarget,
    'interviewFocus' : InterviewFocus,
    'weekNumber' : WeekNumber,
    'topics' : IDL.Vec(Topic),
    'projectSuggestion' : ProjectSuggestion,
  });
  const ProjectName = IDL.Text;
  const TechStack = IDL.Text;
  const Project = IDL.Record({
    'name' : ProjectName,
    'description' : IDL.Text,
    'techStack' : IDL.Vec(TechStack),
  });
  const CodingStats = IDL.Record({
    'totalEasyProblemsSolved' : IDL.Nat,
    'totalHardProblemsSolved' : IDL.Nat,
    'totalMediumProblemsSolved' : IDL.Nat,
    'totalProblemsSolved' : IDL.Nat,
    'optimizationImprovementPercent' : IDL.Nat,
    'completedProjects' : IDL.Vec(Project),
    'longestStreakDays' : IDL.Nat,
    'consistencyScore' : IDL.Nat,
    'currentDayStreak' : IDL.Nat,
  });
  const Optimization = IDL.Text;
  const Language = IDL.Text;
  const EdgeCase = IDL.Text;
  const TleRiskLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Complexity = IDL.Text;
  const Time = IDL.Int;
  const SubmissionId = IDL.Nat64;
  const CodeSubmission = IDL.Record({
    'problemTitle' : IDL.Text,
    'optimizationSuggestions' : IDL.Vec(Optimization),
    'language' : Language,
    'codeText' : IDL.Text,
    'edgeCases' : IDL.Vec(EdgeCase),
    'tleRiskLevel' : TleRiskLevel,
    'timeComplexity' : Complexity,
    'submissionTime' : Time,
    'submissionId' : SubmissionId,
    'spaceComplexity' : Complexity,
  });
  const JobRole = IDL.Text;
  const ResumeStrengthBreakdown = IDL.Record({
    'problemSolving' : IDL.Nat8,
    'projectStrength' : IDL.Nat8,
    'consistency' : IDL.Nat8,
    'languageDepth' : IDL.Nat8,
    'advancedProblemRatio' : IDL.Nat8,
    'optimization' : IDL.Nat8,
  });
  const ResumeHeader = IDL.Record({
    'name' : IDL.Text,
    'graduationYear' : IDL.Nat,
    'email' : IDL.Text,
    'university' : IDL.Text,
  });
  const ResumeData = IDL.Record({
    'keyStrengths' : IDL.Vec(IDL.Text),
    'strengthBreakdown' : ResumeStrengthBreakdown,
    'technicalSkills' : IDL.Vec(IDL.Text),
    'projects' : IDL.Vec(Project),
    'strengthScore' : IDL.Nat8,
    'codingAchievements' : IDL.Text,
    'header' : ResumeHeader,
  });
  const CareerPath = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const SkillLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
    'competitive' : IDL.Null,
  });
  const StudentProfile = IDL.Record({
    'primaryLanguages' : IDL.Vec(Language),
    'name' : IDL.Text,
    'graduationYear' : IDL.Nat,
    'email' : IDL.Text,
    'university' : IDL.Text,
    'focusTopics' : IDL.Vec(Topic),
  });
  const ComprehensiveUserRecordView = IDL.Record({
    'roadmap' : IDL.Vec(RoadmapEntry),
    'codingStats' : CodingStats,
    'skillGaps' : IDL.Vec(IDL.Text),
    'submissions' : IDL.Vec(CodeSubmission),
    'recommendedJobRoles' : IDL.Vec(JobRole),
    'resumeData' : ResumeData,
    'careerPathSuggestions' : IDL.Vec(CareerPath),
    'skillLevel' : SkillLevel,
    'profile' : StudentProfile,
  });
  const UserId = IDL.Principal;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptCycles' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUserRecords' : IDL.Func(
        [],
        [IDL.Vec(ComprehensiveUserRecordView)],
        ['query'],
      ),
    'getAllUserRecordsByEmail' : IDL.Func(
        [],
        [IDL.Vec(ComprehensiveUserRecordView)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCareerPathSuggestions' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
    'getCodingStats' : IDL.Func([], [CodingStats], ['query']),
    'getProfile' : IDL.Func([], [StudentProfile], ['query']),
    'getRecommendedJobRoles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getResumeData' : IDL.Func([], [ResumeData], ['query']),
    'getResumeStrengthBreakdown' : IDL.Func(
        [],
        [ResumeStrengthBreakdown],
        ['query'],
      ),
    'getResumeStrengthScore' : IDL.Func([], [IDL.Nat8], ['query']),
    'getRoadmap' : IDL.Func([], [IDL.Vec(RoadmapEntry)], ['query']),
    'getSkillGaps' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSkillLevel' : IDL.Func([], [SkillLevel], ['query']),
    'getSubmissionById' : IDL.Func([SubmissionId], [CodeSubmission], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getUserRecordById' : IDL.Func(
        [UserId],
        [ComprehensiveUserRecordView],
        ['query'],
      ),
    'getVersion' : IDL.Func([], [IDL.Text], ['query']),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSubmissionsPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(CodeSubmission)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
    'submitCode' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          TleRiskLevel,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [CodeSubmission],
        [],
      ),
    'updateCodingStats' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(Project),
        ],
        [CodingStats],
        [],
      ),
    'updateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [StudentProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };