/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ResumeStrengthBreakdown {
    problemSolving: number;
    projectStrength: number;
    consistency: number;
    languageDepth: number;
    advancedProblemRatio: number;
    optimization: number;
}
export type Time = bigint;
export interface CodeSubmission {
    problemTitle: string;
    optimizationSuggestions: Array<Optimization>;
    language: Language;
    codeText: string;
    edgeCases: Array<EdgeCase>;
    tleRiskLevel: TleRiskLevel;
    timeComplexity: Complexity;
    submissionTime: Time;
    submissionId: SubmissionId;
    spaceComplexity: Complexity;
}
export type InterviewFocus = string;
export type Language = string;
export type ProjectName = string;
export type SubmissionId = bigint;
export type Complexity = string;
export type JobRole = string;
export interface ComprehensiveUserRecordView {
    roadmap: Array<RoadmapEntry>;
    codingStats: CodingStats;
    skillGaps: Array<string>;
    submissions: Array<CodeSubmission>;
    recommendedJobRoles: Array<JobRole>;
    resumeData: ResumeData;
    careerPathSuggestions: Array<CareerPath>;
    skillLevel: SkillLevel;
    profile: StudentProfile;
}
export interface CareerPath {
    name: string;
    description: string;
}
export interface ResumeData {
    keyStrengths: Array<string>;
    strengthBreakdown: ResumeStrengthBreakdown;
    technicalSkills: Array<string>;
    projects: Array<Project>;
    strengthScore: number;
    codingAchievements: string;
    header: ResumeHeader;
}
export type EdgeCase = string;
export type ProjectSuggestion = string;
export interface ResumeHeader {
    name: string;
    graduationYear: bigint;
    email: string;
    university: string;
}
export interface RoadmapEntry {
    problemsTargetCount: bigint;
    optimizationTargetPercent: OptimizationTarget;
    interviewFocus: InterviewFocus;
    weekNumber: WeekNumber;
    topics: Array<Topic>;
    projectSuggestion: ProjectSuggestion;
}
export interface CodingStats {
    totalEasyProblemsSolved: bigint;
    totalHardProblemsSolved: bigint;
    totalMediumProblemsSolved: bigint;
    totalProblemsSolved: bigint;
    optimizationImprovementPercent: bigint;
    completedProjects: Array<Project>;
    longestStreakDays: bigint;
    consistencyScore: bigint;
    currentDayStreak: bigint;
}
export type UserId = Principal;
export interface StudentProfile {
    primaryLanguages: Array<Language>;
    name: string;
    graduationYear: bigint;
    email: string;
    university: string;
    focusTopics: Array<Topic>;
}
export type OptimizationTarget = number;
export type TechStack = string;
export type WeekNumber = bigint;
export type Topic = string;
export interface Project {
    name: ProjectName;
    description: string;
    techStack: Array<TechStack>;
}
export type Optimization = string;
export enum SkillLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced",
    competitive = "competitive"
}
export enum TleRiskLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptCycles(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllUserRecords(): Promise<Array<ComprehensiveUserRecordView>>;
    getAllUserRecordsByEmail(): Promise<Array<ComprehensiveUserRecordView>>;
    getCallerUserProfile(): Promise<StudentProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCareerPathSuggestions(): Promise<Array<CareerPath>>;
    getCodingStats(): Promise<CodingStats>;
    getProfile(): Promise<StudentProfile>;
    getRecommendedJobRoles(): Promise<Array<string>>;
    getResumeData(): Promise<ResumeData>;
    getResumeStrengthBreakdown(): Promise<ResumeStrengthBreakdown>;
    getResumeStrengthScore(): Promise<number>;
    getRoadmap(): Promise<Array<RoadmapEntry>>;
    getSkillGaps(): Promise<Array<string>>;
    getSkillLevel(): Promise<SkillLevel>;
    getSubmissionById(submissionId: SubmissionId): Promise<CodeSubmission>;
    getUserProfile(user: Principal): Promise<StudentProfile | null>;
    getUserRecordById(userId: UserId): Promise<ComprehensiveUserRecordView>;
    getVersion(): Promise<string>;
    getWalletBalance(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    listSubmissionsPaginated(pageSize: bigint, pageIndex: bigint): Promise<Array<CodeSubmission>>;
    saveCallerUserProfile(profile: StudentProfile): Promise<void>;
    submitCode(language: string, problemTitle: string, codeText: string, timeComplexity: string, spaceComplexity: string, tleRisk: TleRiskLevel, edgeCases: Array<string>, optimizations: Array<string>): Promise<CodeSubmission>;
    updateCodingStats(totalProblems: bigint, easy: bigint, medium: bigint, hard: bigint, longestStreak: bigint, currentStreak: bigint, consistency: bigint, optimization: bigint, completedProjects: Array<Project>): Promise<CodingStats>;
    updateProfile(name: string, email: string, university: string, graduationYear: bigint, primaryLanguages: Array<string>, focusTopics: Array<string>): Promise<StudentProfile>;
}
import type { CareerPath as _CareerPath, CodeSubmission as _CodeSubmission, CodingStats as _CodingStats, Complexity as _Complexity, ComprehensiveUserRecordView as _ComprehensiveUserRecordView, EdgeCase as _EdgeCase, JobRole as _JobRole, Language as _Language, Optimization as _Optimization, ResumeData as _ResumeData, RoadmapEntry as _RoadmapEntry, SkillLevel as _SkillLevel, StudentProfile as _StudentProfile, SubmissionId as _SubmissionId, Time as _Time, TleRiskLevel as _TleRiskLevel, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptCycles(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptCycles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptCycles();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllUserRecords(): Promise<Array<ComprehensiveUserRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserRecords();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserRecords();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserRecordsByEmail(): Promise<Array<ComprehensiveUserRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserRecordsByEmail();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserRecordsByEmail();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCareerPathSuggestions(): Promise<Array<CareerPath>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCareerPathSuggestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCareerPathSuggestions();
            return result;
        }
    }
    async getCodingStats(): Promise<CodingStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getCodingStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCodingStats();
            return result;
        }
    }
    async getProfile(): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return result;
        }
    }
    async getRecommendedJobRoles(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedJobRoles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedJobRoles();
            return result;
        }
    }
    async getResumeData(): Promise<ResumeData> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumeData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumeData();
            return result;
        }
    }
    async getResumeStrengthBreakdown(): Promise<ResumeStrengthBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumeStrengthBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumeStrengthBreakdown();
            return result;
        }
    }
    async getResumeStrengthScore(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumeStrengthScore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumeStrengthScore();
            return result;
        }
    }
    async getRoadmap(): Promise<Array<RoadmapEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoadmap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoadmap();
            return result;
        }
    }
    async getSkillGaps(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillGaps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillGaps();
            return result;
        }
    }
    async getSkillLevel(): Promise<SkillLevel> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillLevel();
                return from_candid_SkillLevel_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillLevel();
            return from_candid_SkillLevel_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissionById(arg0: SubmissionId): Promise<CodeSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionById(arg0);
                return from_candid_CodeSubmission_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionById(arg0);
            return from_candid_CodeSubmission_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRecordById(arg0: UserId): Promise<ComprehensiveUserRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRecordById(arg0);
                return from_candid_ComprehensiveUserRecordView_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRecordById(arg0);
            return from_candid_ComprehensiveUserRecordView_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVersion(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getVersion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVersion();
            return result;
        }
    }
    async getWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listSubmissionsPaginated(arg0: bigint, arg1: bigint): Promise<Array<CodeSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubmissionsPaginated(arg0, arg1);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubmissionsPaginated(arg0, arg1);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: StudentProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitCode(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: TleRiskLevel, arg6: Array<string>, arg7: Array<string>): Promise<CodeSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCode(arg0, arg1, arg2, arg3, arg4, to_candid_TleRiskLevel_n16(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_CodeSubmission_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCode(arg0, arg1, arg2, arg3, arg4, to_candid_TleRiskLevel_n16(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_CodeSubmission_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCodingStats(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: Array<Project>): Promise<CodingStats> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCodingStats(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCodingStats(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Array<string>, arg5: Array<string>): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_CodeSubmission_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CodeSubmission): CodeSubmission {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ComprehensiveUserRecordView_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComprehensiveUserRecordView): ComprehensiveUserRecordView {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_SkillLevel_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillLevel): SkillLevel {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TleRiskLevel_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TleRiskLevel): TleRiskLevel {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roadmap: Array<_RoadmapEntry>;
    codingStats: _CodingStats;
    skillGaps: Array<string>;
    submissions: Array<_CodeSubmission>;
    recommendedJobRoles: Array<_JobRole>;
    resumeData: _ResumeData;
    careerPathSuggestions: Array<_CareerPath>;
    skillLevel: _SkillLevel;
    profile: _StudentProfile;
}): {
    roadmap: Array<RoadmapEntry>;
    codingStats: CodingStats;
    skillGaps: Array<string>;
    submissions: Array<CodeSubmission>;
    recommendedJobRoles: Array<JobRole>;
    resumeData: ResumeData;
    careerPathSuggestions: Array<CareerPath>;
    skillLevel: SkillLevel;
    profile: StudentProfile;
} {
    return {
        roadmap: value.roadmap,
        codingStats: value.codingStats,
        skillGaps: value.skillGaps,
        submissions: from_candid_vec_n6(_uploadFile, _downloadFile, value.submissions),
        recommendedJobRoles: value.recommendedJobRoles,
        resumeData: value.resumeData,
        careerPathSuggestions: value.careerPathSuggestions,
        skillLevel: from_candid_SkillLevel_n11(_uploadFile, _downloadFile, value.skillLevel),
        profile: value.profile
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    problemTitle: string;
    optimizationSuggestions: Array<_Optimization>;
    language: _Language;
    codeText: string;
    edgeCases: Array<_EdgeCase>;
    tleRiskLevel: _TleRiskLevel;
    timeComplexity: _Complexity;
    submissionTime: _Time;
    submissionId: _SubmissionId;
    spaceComplexity: _Complexity;
}): {
    problemTitle: string;
    optimizationSuggestions: Array<Optimization>;
    language: Language;
    codeText: string;
    edgeCases: Array<EdgeCase>;
    tleRiskLevel: TleRiskLevel;
    timeComplexity: Complexity;
    submissionTime: Time;
    submissionId: SubmissionId;
    spaceComplexity: Complexity;
} {
    return {
        problemTitle: value.problemTitle,
        optimizationSuggestions: value.optimizationSuggestions,
        language: value.language,
        codeText: value.codeText,
        edgeCases: value.edgeCases,
        tleRiskLevel: from_candid_TleRiskLevel_n9(_uploadFile, _downloadFile, value.tleRiskLevel),
        timeComplexity: value.timeComplexity,
        submissionTime: value.submissionTime,
        submissionId: value.submissionId,
        spaceComplexity: value.spaceComplexity
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): TleRiskLevel {
    return "low" in value ? TleRiskLevel.low : "high" in value ? TleRiskLevel.high : "medium" in value ? TleRiskLevel.medium : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} | {
    competitive: null;
}): SkillLevel {
    return "intermediate" in value ? SkillLevel.intermediate : "beginner" in value ? SkillLevel.beginner : "advanced" in value ? SkillLevel.advanced : "competitive" in value ? SkillLevel.competitive : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ComprehensiveUserRecordView>): Array<ComprehensiveUserRecordView> {
    return value.map((x)=>from_candid_ComprehensiveUserRecordView_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CodeSubmission>): Array<CodeSubmission> {
    return value.map((x)=>from_candid_CodeSubmission_n7(_uploadFile, _downloadFile, x));
}
function to_candid_TleRiskLevel_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TleRiskLevel): _TleRiskLevel {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TleRiskLevel): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == TleRiskLevel.low ? {
        low: null
    } : value == TleRiskLevel.high ? {
        high: null
    } : value == TleRiskLevel.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
